[workspace]
members = [
  "iapyx",
  "vitup",
  "valgrind",
  "integration-tests",
  "mainnet-tools",
  "registration-service",
  "registration-verify-service",
  "snapshot-trigger-service",
  "signals-handler"  
]
